#
# This is a synology util lib,
#

obj-$(CONFIG_SYNO_DEBUG_FLAG) += syno_process_name_get.o
obj-$(CONFIG_SYNO_PLUGIN_INTERFACE) += syno_plugin.o
obj-$(CONFIG_SYNO_SATA_REMAP) += syno_remap_idx_get.o
obj-$(CONFIG_SYNO_PCI_HOST_SATA_CACHE) += syno_shift_remap_table.o
